# Generated by Django 4.2.3 on 2023-07-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('po_number', models.IntegerField(default=0)),
                ('container_number', models.IntegerField(default=0)),
                ('outbound_number', models.IntegerField(default=0)),
                ('reference_number', models.IntegerField(default=0)),
                ('note_section', models.CharField(max_length=512)),
                ('date_time', models.DateTimeField(verbose_name='Request Date')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.employee')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.request')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Actions_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField(verbose_name='Action Date/Time')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.employee')),
            ],
        ),
    ]
