# Generated by Django 4.2.3 on 2023-07-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='outbound_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='actions_log',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request',
            name='check_in_time',
            field=models.TimeField(null=True, verbose_name='Checked In'),
        ),
        migrations.AddField(
            model_name='request',
            name='completed_time',
            field=models.TimeField(null=True, verbose_name='Time Completed'),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='dock_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='docked_time',
            field=models.TimeField(null=True, verbose_name='Docked Time'),
        ),
        migrations.AddField(
            model_name='request',
            name='driver_phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='load_type',
            field=models.CharField(default='full', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='trailer_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='note_section',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
