# Generated by Django 4.2.3 on 2023-09-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='request',
            name='warehouse',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='members.warehouse'),
        ),
    ]
