# Generated by Django 4.2.3 on 2023-07-18 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_request_outbound_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField(verbose_name='Action Date/Time')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='warehouse_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='role',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.request'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.employee'),
        ),
        migrations.DeleteModel(
            name='Actions_Log',
        ),
        migrations.AddField(
            model_name='actionslog',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.employee'),
        ),
    ]
