# Generated by Django 4.2.3 on 2023-09-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_request_email_alter_request_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.warehouse'),
        ),
    ]
