# Generated by Django 4.2.3 on 2023-07-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_actionslog_remove_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.employee'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.request'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.warehouse'),
        ),
    ]
