# Generated by Django 4.2.3 on 2024-04-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_request_check_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='po_number',
        ),
        migrations.AddField(
            model_name='request',
            name='ref_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
