# Generated by Django 4.2.3 on 2023-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_role_employee_alter_schedule_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='trailer_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
