# Generated by Django 4.2.3 on 2024-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_request_po_number_request_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sms_consent',
            field=models.BooleanField(default=False),
        ),
    ]
