# Generated by Django 4.2.3 on 2024-05-07 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0005_request_sms_consent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ApprovalLog',
        ),
    ]
