services:
  # backend-dev:
  #   build:
  #     context: .
  #   container_name: backend_c_dev
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static

  # frontend-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.node
  #     target: development
  #   container_name: frontend_c_dev
  #   command: npm run dev -- --host
  #   ports:
  #     - 3004:5173
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on: 
  #     - backend-dev
  #   stdin_open: true
  #   tty: true
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: react_frontend
    restart: always
    ports: 
      - 3000:80
    volumes:
      - backend_static:/app/static
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  backend_static: