# Generated by Django 4.2.3 on 2024-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_request_container_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked In'),
        ),
        migrations.AlterField(
            model_name='request',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Completed'),
        ),
        migrations.AlterField(
            model_name='request',
            name='docked_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Docked Time'),
        ),
    ]
