# Generated by Django 4.2.3 on 2024-05-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_schedule_approvallog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalLog',
        ),
    ]
