# Generated by Django 4.2.3 on 2024-05-08 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_approvallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNumberLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sms_number', models.CharField(max_length=12)),
                ('consent', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
