# Generated by Django 4.2.3 on 2026-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_smsnumberlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='color',
            field=models.CharField(default='#02B40B', max_length=7),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
    ]
