# Generated by Django 4.2.3 on 2026-03-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_warehouse_color_warehouse_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
