# Generated by Django 4.2.3 on 2026-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_request_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cancelled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='request',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
