# Generated by Django 4.2.3 on 2026-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_request_cancelled_time_request_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='appointments_per_slot',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
