# Generated by Django 4.2.3 on 2026-04-11 17:25

from django.db import migrations
import uuid

def populate_customers(apps, schema_editor):
    Request = apps.get_model('members', 'Request')
    Customer = apps.get_model('members', 'Customer')

    customer_map = {}
    for req in Request.objects.filter(customer_name__isnull=False).exclude(customer_name=''):
        name = req.customer_name.strip()
        if name not in customer_map:
            customer_map[name] = Customer.objects.create(
                id=uuid.uuid4(),
                customer_name=name,
                email_address='',
                send_email_updates=False,
                active=True,
            )
        req.customer = customer_map[name]
        req.save(update_fields=['customer'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_customer_request_customer'),
    ]

    operations = [
        migrations.RunPython(populate_customers, migrations.RunPython.noop),
    ]
