# Generated by Django 4.2.3 on 2026-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_populate_customer_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ref_number',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
