# Generated by Django 4.2.3 on 2026-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_request_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='appointment_length',
            field=models.IntegerField(default=15),
        ),
    ]
