# Generated by Django 4.2.3 on 2026-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_request_ref_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['active', 'approved', 'date_time'], name='request_active_approved_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['date_time'], name='request_date_time_idx'),
        ),
    ]
