# Generated by Django 4.2.3 on 2026-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_request_request_active_approved_dt_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='load_config',
            field=models.CharField(blank=True, choices=[('Palletized', 'Palletized'), ('Floor Loaded', 'Floor Loaded')], max_length=32, null=True),
        ),
    ]
