# Generated by Django 4.2.3 on 2026-09-30 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0020_request_load_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('declined', 'Declined'), ('edited', 'Edited'), ('checked_in', 'Checked in'), ('docked', 'Docked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_events', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='members.request')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('occurred_at'), descending=True, nulls_last=True)],
                'indexes': [models.Index(fields=['appointment', 'occurred_at'], name='apptevent_appt_occurred_idx')],
            },
        ),
    ]
