# Generated by Django 4.2.3 on 2026-09-30 02:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_import_approvallog_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=8)),
                ('recipient', models.CharField(max_length=254)),
                ('kind', models.CharField(blank=True, choices=[('new_request', 'New request (to team)'), ('request_confirmation', 'Request confirmation'), ('calendar_event', 'New calendar event (to team)'), ('customer_scheduled', 'Appointment scheduled (to customer)'), ('approval', 'Approval'), ('decline', 'Decline'), ('cancellation', 'Cancellation'), ('dock_ready', 'Dock ready (SMS)'), ('yard_drop', 'Yard drop (SMS)'), ('sms_subscribed', 'SMS subscribed')], max_length=32)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=8)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='members.request')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
