# Generated by Django 4.2.3 on 2026-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('declined', 'Declined'), ('edited', 'Edited'), ('checked_in', 'Checked in'), ('docked', 'Docked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('removed', 'Removed from calendar')], max_length=32),
        ),
    ]
