---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: ctscheduling
spec:
  acme:
    server: $(CERTIFICATE_SERVER)
    email: $(CERTIFICATE_EMAIL)
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctscheduling
  namespace: ctscheduling
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ctschedulinghost
    secretName: ctschedulingtlssecret
  rules:
    - host: ctschedulinghost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ctscheduling
                port:
                  number: 8000